apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: writefluency-ingress
  namespace: writefluency
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - writefluency.com
        - api.writefluency.com
        - minio.writefluency.com
        - minioapi.writefluency.com
      secretName: writefluency-tls
  rules:
    - host: writefluency.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wf-webapp
                port:
                  number: 4200
    - host: api.writefluency.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wf-api
                port:
                  number: 8080
    - host: minio.writefluency.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wf-minio
                port:
                  number: 9001
    - host: minioapi.writefluency.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wf-minio
                port:
                  number: 9000