namespace: writefluency

resources:
- wf-minio
- wf-minio-init
- wf-postgres
- wf-db-migrator
- wf-api
- wf-news-worker
- wf-webapp
- namespace.yaml

generatorOptions:
  disableNameSuffixHash: true


