resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: wf-webapp-env
  literals:
    - NODE_ENV=production
    - services__wf-api__http__0=http://wf-api:8080
    - services__wf-api__apihttp__0=wf-api:5000
    - services__wf-api__apihttps__0=wf-api:5001
    - PORT=4200
