---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wf-webapp
  labels:
    app: wf-webapp
spec:
  template:
    metadata:
      labels:
        app: wf-webapp
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: wf-webapp
        envFrom:
        - configMapRef:
            name: wf-webapp-env
        - secretRef:
            name: wf-app-secrets