---
apiVersion: v1
kind: Service
metadata:
  name: wf-api
spec:
  type: ClusterIP
  selector:
    app: wf-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  - name: apihttp
    port: 5000
    targetPort: 5000
  - name: apihttps
    port: 5001
    targetPort: 5001
